### ISSUE TITLE
Can't verify interface mock got called

### ISSUE THREAD

**Issue by sennett** [NagRock/ts-mockito#157]
Thanks for this library.  I'm having some trouble verifying that a mock was called.

```
import Player from './Player'
import IBoard from './IBoard'
import { mock, verify, anything } from 'ts-mockito'

describe('Player', () => {
  it('sets a piece on the board', () => {
    const mockBoard: IBoard = mock<IBoard>()
    const player = new Player(mockBoard)
    verify(mockBoard.setPiece(anything())).called()
  })
})
```

`Player.ts`

```
import IPlayer from './IPlayer'
import IBoard from './IBoard'
import IPiece from './IPiece'
import Piece from './Piece'

class Player implements IPlayer {
  constructor (private board: IBoard) {
    this.piece = new Piece(this)
    this.board.setPiece(this.piece)
  }
  private piece: IPiece
}

export default Player
```

Expected: the test pass as `board.setPiece` is called.
Actual: the tests fail with this output:

```
 FAIL  src/game/Player.test.ts
  ● Player › sets a piece on the board

    Expected "setPiece(anything())" to be called at least 1 time(s). But has been called 0 time(s).

       7 |     const mockBoard: IBoard = mock<IBoard>()
       8 |     const player = new Player(mockBoard)
    >  9 |     verify(mockBoard.setPiece(anything())).called()
         |                                            ^
      10 |   })
      11 | })
      12 | 

      at MethodStubVerificator.Object.<anonymous>.MethodStubVerificator.atLeast (node_modules/ts-mockito/src/MethodStubVerificator.ts:43:19)
      at MethodStubVerificator.Object.<anonymous>.MethodStubVerificator.called (node_modules/ts-mockito/src/MethodStubVerificator.ts:12:14)
      at Object.called (src/game/Player.test.ts:9:44)
```

Please let me know where I'm going wrong and I'll make a PR to update the docs.  The readme currently says "Mocking interfaces requires Proxy implementation".  I'm not sure what this means but possibly it's related.

**Comment by NagRock** [comment]
You've forgotten to use `instance` function:

`const player = new Player(instance(mockBoard))`

This is the biggest difference with Java mockito. We got mock to set mock behaviors and verify expectations. But we use instance to pass object to real implementation .

**Comment by sennett** [comment]
Nice one thanks. Docs PR here: https://github.com/NagRock/ts-mockito/pull/158
