### ISSUE TITLE
How to mock a fonction that returns an observable ?

### ISSUE THREAD

**Issue by jpfradet** [NagRock/ts-mockito#164]
Hi,

I'm trying to mock my function that returns an observable of type any and i get this error

```
TypeError: this.serviceBackend.obtenirListeEquipe(...).toPromise is not a function
    at EquipeService../src/app/equipe/services/equipe.service.ts.EquipeService.construireListeEquipe (http://localhost:9876/_karma_webpack_/webpack:/src/app/equipe/services/equipe.service.ts:48:8)
    at EquipeService../src/app/equipe/services/equipe.service.ts.EquipeService.obtenirListe (http://localhost:9876/_karma_webpack_/webpack:/src/app/equipe/services/equipe.service.ts:30:40)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/src/app/equipe/services/equipe-service.ts-mockito.spec.ts:32:15)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:391:1)
    at ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-testing.js:289:1)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:390:1)
    at Zone../node_modules/zone.js/dist/zone.js.Zone.run (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:150:1)
    at runInTestZone (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-testing.js:510:1)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-testing.js:525:1)
    at attempt (http://localhost:9876/absoluteD:/git/depot01/OW/OW03/OW03.ActiviteOperationnelle.IU/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4478:46)
```

My Class that i want to test :

```
@Injectable()
export class EquipeService implements IEquipeService, OnDestroy {

  listeEquipe$: Subject<Equipe[]>;

  constructor(private serviceBackend: BackendService) {
     this.listeEquipe$ = new Subject<Equipe[]>();
  }

  obtenirListe(): Observable<Equipe[]> {
    const listeEquipe: Equipe[] = this.construireListeEquipe();
    return of(listeEquipe);
  }

  private rafraichirListe(): void {
    const liste: Equipe[] = this.construireListeEquipe();
    this.listeEquipe$.next(liste);
  }

  private construireListeEquipe(): Equipe[] {
    const listeEquipe: Equipe[] = [];
    this.serviceBackend
      .obtenirListeEquipe()
      .toPromise()
      .then((objetJSON: any) => {
        objetJSON.forEach((equipeJSON: any) => {
          const equipe: Equipe = new Equipe();
          equipe.nom = equipeJSON.nom;
          listeEquipe.push(equipe);
        });
      });
    return listeEquipe;
  }
```

My .spec.ts that test it :

```
describe('EquipeService using ts-mockito', () => {
  let service: EquipeService;
  let mockServiceBackend: BackendService;

  const equipeBidon: any = {
    nom: 'Équipe 4',
    description: '1',
    numeroCentreResponsabilite: '1',
    logonResponsable: '1'
  };
  const listeEquipeBidon$: Observable<any> = of([equipeBidon]);

  beforeEach(async(() => {
    mockServiceBackend = mock(BackendService);
    service = new EquipeService(mockServiceBackend);
  }));

  describe('obtenirListe()', () => {
   
    fit('devrait appeler la fonction BackendService.ObtenirListeEquipe()', () => {
      // Arranger
      when(mockServiceBackend.obtenirListeEquipe()).thenReturn(listeEquipeBidon$);

      // Agir
      service.obtenirListe();

      // Affirmer
      verify(mockServiceBackend.obtenirListeEquipe()).once();
    });
```

The dependency i want to mock : 

```
@Injectable()
export class BackendService
  implements IBackendService {
  constructor(
    private depotEquipeService: DepotEquipeService,
    private clientHttp: HttpClient
  ) {
  }

  obtenirListeEquipe(): Observable<any> {
    return this.depotEquipeService.obtenirDepot();
  }
```

I can achieve this with Jasmine SpyOn : 
```

it('devrait appeler la fonction BackendService.ObtenirListeEquipe()', () => {
      // Arranger
      spyOn(serviceBackend, 'obtenirListeEquipe').and.returnValue(listeEquipeBidon$);

      // Agir
      service.obtenirListe();
      // tick();

      // Affirmer
      expect(serviceBackend.obtenirListeEquipe).toHaveBeenCalled();
    });
```

Thank you to anyone reading this ! :)

**Comment by NagRock** [comment]
You need to pass `instance` of mock not mock itself: 

`service = new EquipeService(instance(mockServiceBackend));`
