### ISSUE TITLE
Spying on an object says "TypeError: Cannot redefined property"

### ISSUE THREAD

**Issue by iangregsondev** [NagRock/ts-mockito#167]
Hi,

I have managed to spy on a couple of objects from node but lately I tried with a mapping library called morphism and i get the following error

```
Type error: Cannot redefined morph
```

I am doing the following

```
import * as morphism from "morphism"
```

![image](https://user-images.githubusercontent.com/2370364/68670295-dc4e6500-054c-11ea-96ec-1e989bf0007c.png)

The probem is, this happens on the spy(instance) - see above... so I am not sure what i can do.

It seems its trying to override a type.

I also checked the issues on the github for that library and it seems jest can mock this but I really didn't want to mix mocking frameworks.

Anybody have an idea if I can do anything ?

**Comment by iangregsondev** [comment]
I have some stacktrace if it helps

```
TypeError: Cannot redefine property: morph
[Info]          at Function.defineProperty (<anonymous>)
[Info]        at Spy.Object.<anonymous>.Spy.createInstancePropertyDescriptorListener (node_modules/ts-mockito/src/Spy.ts:53:16)
[Info]        at node_modules/ts-mockito/src/Mock.ts:125:26
[Info]            at Array.forEach (<anonymous>)
[Info]        at node_modules/ts-mockito/src/Mock.ts:118:65
[Info]            at Array.forEach (<anonymous>)
[Info]        at Spy.Object.<anonymous>.Mocker.processProperties (node_modules/ts-mockito/src/Mock.ts:117:58)
[Info]        at new Spy (node_modules/ts-mockito/src/Spy.ts:14:18)
[Info]        at Object.spy (node_modules/ts-mockito/src/ts-mockito.ts:32:12)
```

**Comment by iangregsondev** [comment]
and I presume its this from the source

```
export function morph<Target>(schema: Schema<Target>, type?: Constructable<Target>) {
  const mapper = transformItems(schema, type);
  return decorator(mapper);
}
```

line 205 https://github.com/nobrainr/morphism/blob/ef1ceca2977378253b52ce4045262b383e4504fb/src/morphism.ts

**Comment by iangregsondev** [comment]
Closing this issue, as it has gone unanswered for over 6 months, and I have since worked around it.
