### ISSUE TITLE
mocking anonymous methods on interface

### ISSUE THREAD

**Issue by xenoterracide** [NagRock/ts-mockito#178]
```
testContainer.register(Beans.CEC_LOCATION, {
    useFactory: (c) => {
      const location = mock<ContentfulEntryConnector<ContentfulLocationFields>>();
      const entry = mock<Entry<ContentfulLocationFields>>();
      when(entry.fields.id).thenReturn('42');
      when(location(anyString()).get()).thenResolve(entry);
      return location;
    },
  });
});
```

```
export interface ContentfulEntryConnector<T> {
  (id: string): ContentfulEntryContext<T>;

  all(): Promise<Array<Entry<T>|undefined>>;

  byField(name: keyof T, value: T[keyof T]): ContentfulEntryContext<T>;
}
```

```
TypeError: location is not a function

    at Object.useFactory (/Users/calebcushing/IdeaProjects/service-graph/src/__tests__/LocationUnitTest.ts:18:12)
    at InternalDependencyContainer.resolveRegistration (/Users/calebcushing/IdeaProjects/service-graph/node_modules/tsyringe/dist/cjs/dependency-container.js:105:46)
    at InternalDependencyContainer.resolve (/Users/calebcushing/IdeaProjects/service-graph/node_modules/tsyringe/dist/cjs/dependency-container.js:76:25)
    at paramInfo.map.param (/Users/calebcushing/IdeaProjects/service-graph/node_modules/tsyringe/dist/cjs/dependency-container.js:183:25)
    at Array.map (<anonymous>)
    at InternalDependencyContainer.construct (/Users/calebcushing/IdeaProjects/service-graph/node_modules/tsyringe/dist/cjs/dependency-container.js:177:34)
    at InternalDependencyContainer.resolve (/Users/calebcushing/IdeaProjects/service-graph/node_modules/tsyringe/dist/cjs/dependency-container.js:78:21)
    at ApolloServer.context (/Users/calebcushing/IdeaProjects/service-graph/src/getApolloServerConfig.ts:130:36)
    at ApolloServer.<anonymous> (/Users/calebcushing/IdeaProjects/service-graph/node_modules/apollo-server-core/src/ApolloServer.ts:736:24)
    at Generator.next (<anonymous>)
```

**Comment by xenoterracide** [comment]
didn't realize I had to use the `instance` to create an instance
