### ISSUE TITLE
Is it possible to mock an Observable?

### ISSUE THREAD

**Issue by hugadams** [NagRock/ts-mockito#62]
Hi,

I really like ts-mockito, so thank you for this library.  Following this [guide on stubbing Observables in angular 2](https://medium.com/@paynoattn/simple-observable-unit-testing-in-angular2-43c4f4a0bfe2), it seemed straightforward to do a similar thing with mocks.  

Consider a service with a method, `getObservable()`, that returns an `Observable<SomeType>`, where `SomeType` is simply a TS interface.  How would one setup a mocked object to override this method?  

First I created some mocked data of type `SomeType`:

    const mockedData: SomeType = {foo: 'bar'}

And then I stub the method call

    when(mockedService.getData('1')).thenReturn(Observable.of(mockedData))

But this gives a runtime error (compiler has no problem with it...)

```
TypeError: Cannot read property 'methodStubCollection' of null
    at http://localhost:9876/_karma_webpack_/webpack:/C:/Users/xbbl2q8/Desktop/development/ears-ui/ewh-earsui-angularui/node_modules/ts-mockito/lib/MethodStubSetter.js:18:1
    at Array.forEach (<anonymous>)
    at MethodStubSetter.webpackJsonp.../../../../ts-mockito/lib/MethodStubSetter.js.MethodStubSetter.thenReturn (http://localhost:9876/_karma_webpack_/webpack:/C:/Users/xbbl2q8/Desktop/development/ears-ui/ewh-earsui-angularui/node_modules/ts-mockito/lib/MethodStubSetter.js:17:1)
    at Object.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/C:/Users/xbbl2q8/Desktop/development/ears-ui/ewh-earsui-angularui/src/app/shared/services/activiti/activiti.handler.spec.ts:82:37)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/C:/Users/xbbl2q8/Desktop/development/ears-ui/ewh-earsui-angularui/node_modules/zone.js/dist/zone.js:392:1)
    at ProxyZoneSpec.webpackJsonp.../../../../zone.js/dist/proxy.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/C:/Users/xbbl2q8/Desktop/development/ears-ui/ewh-earsui-angularui/node_modules/zone.js/dist/proxy.js:79:1)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/C:/Users/xbbl2q8/Desktop/development/ears-ui/ewh-earsui-angularui/node_modules/zone.js/dist/zone.js:391:1)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run (http://localhost:9876/_karma_webpack_/webpack:/C:/Users/xbbl2q8/Desktop/development/ears-ui/ewh-earsui-angularui/node_modules/zone.js/dist/zone.js:142:1)
    at Object.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/C:/Users/xbbl2q8/Desktop/development/ears-ui/ewh-earsui-angularui/node_modules/zone.js/dist/jasmine-patch.js:104:1) 
```

Anyone ever seen something similar?

Also posted on SO (https://stackoverflow.com/questions/47035242/angular-observable-stubbing-doesnt-work-in-ts-mockito)

Dropping into the source, it looks like `MethodStubSetter.js` is not setting`_this.methodStub` when called  via the Observable.of() method.

**Comment by hugadams** [comment]
Sorry, was stubbing the instance (mockedService) instead of the class (mock(ActivityService))
