### ISSUE TITLE
Unable to mock classes that make call to 'toString()' 

### ISSUE THREAD

**Issue by simon-weimann** [NagRock/ts-mockito#73]
When mocking a class that contains a method, that internally calls `toString()` I get the following error 

```
TypeError: methodStub.hasMatchingInAnyGroup is not a function
	    at Mocker.webpackJsonp.../../../../ts-mockito/lib/Mock.js.Mocker.getMethodStub home/dev/src/ui/~/ts-mockito/lib/Mock.js:183:1)
	    at Proxy.<anonymous> home/dev/src/ui/~/ts-mockito/lib/Mock.js:115:1)
```

I guess that is related to the same problem like in https://github.com/NagRock/ts-mockito/issues/28 

When I was debugging the ts-mockito code, I could see, that https://github.com/NagRock/ts-mockito/blob/master/src/utils/MockableFunctionsFinder.ts returned a positive match on my dummy() function that contains the `toString()` invocation.

This is a jasmine test example I used to reproduce the error:
```
import {instance, mock} from "ts-mockito";

describe("toString", () => {

	it("should not break on toString", () => {
		const dummyMock: Dummy = mock(Dummy);
		const dummyInstance: Dummy = instance(dummyMock);

		dummyInstance.toString();
	});
});

export class Dummy {

	public dummy(): void {
		window.toString();
	}
}
```

**Comment by NagRock** [comment]
Hi @simon-weimann thanks for reporting this. `ts-mockito` got find function names in code to be able to mock dynamic functions too. Maybe I got to add option to `mock` function to skip dynamic code finder. For example `mock(Dummy).skipDynamicFunctionsFinder()` or maby skip `toString` function as it is generic for all `Objects`. But I'll try to find better solution for that first. Don't want to add dirty hacks.
I guess this is deal breaker for you?

**Comment by simon-weimann** [comment]
Thanks for your reply @NagRock,
it is not that of a big deal breaker. It only is a problem for some of our unit tests when they actually fail (which they shouldn't). It then hides the actual reason for the unit test to break.

Both options seem viable to me.

**Comment by dpinol** [comment]
hi, any news on this? any workaround?

thanks
